### ISSUE TITLE
CommandNotSupportedOnView

### ISSUE THREAD

**Issue by intonet** [MongoDB-Cowboys/Monalize#3]
Hi
./monalize exit during counting docs with error:
`Something went wrong listing (CommandNotSupportedOnView) Namespace ... is a view, not a collection`
Is there any solution for skip views ? 

MongoDB server version: 4.2.2

**Comment by ku9nov** [comment]
Hi @intonet
It is interesting. Thanks for the report)
I will deal with this in the near future.

**Comment by ku9nov** [comment]
hey @intonet 
I added support for skipping views.
You can check?

**Comment by intonet** [comment]
Hi. 
@ku9nov, works well. Thx!

**Comment by ku9nov** [comment]
@intonet great, thx for your response

**Comment by dmgeurts** [comment]
Please could this be included in a new release?

**Comment by ku9nov** [comment]
@dmgeurts Hey, it is done.
https://github.com/MongoDB-Cowboys/Monalize/releases/tag/1.1.2

**Comment by dmgeurts** [comment]
> Hey, it is done.
> https://github.com/MongoDB-Cowboys/Monalize/releases/tag/1.1.2

Thank you! Just found that Ubuntu 20.04 is still on glibc 2.31...

```
./monalize: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./monalize)
./monalize: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./monalize)
```
