### ISSUE TITLE
Cannot connect although it works with mongo shell

### ISSUE THREAD

**Issue by stan-thomas** [MongoDB-Cowboys/Monalize#4]
`monalize -db_uri mongodb://admin:admin@10.1.2.2:27017 --logpath /var/log/mongodb/mongod.log -db_name admin`

The auth details in this command work and it connects. Same machine monalize throws "Connect to MongoDB is impossible. Check if it works and the entered data."

Mongo version 4.4

What needs to be changed?

**Comment by artazar** [comment]
Same issue with me, also mongo 4.4:

    # ./monalize -db_uri 'mongodb://mongo_admin:xxxxx@localhost:27017' -logpath /var/log/mongodb/mongod.log
    2021/04/05 01:14:13 Connect to MongoDB is impossible. Check if it works and the entered data.

**Comment by artazar** [comment]
Should be related to https://github.com/MongoDB-Cowboys/Monalize/pull/2

**Comment by thebionicman1** [comment]
could you guys tell me how you were able to download the tool? I tried the following:
 go build monalize.go
go: github.com/360EntSecGroup-Skylar/excelize@v1.4.1: Get https://proxy.golang.org/github.com/360%21ent%21sec%21group-%21skylar/excelize/@v/v1.4.1.mod: dial tcp 216.58.194.209:443: i/o timeout

**Comment by ku9nov** [comment]
Hey folk.
@stan-thomas 
@artazar 
MongoDB server version: 4.4.4
```
./monalize --db_uri "mongodb://user:passwd@172.xx.xx.xxx:27017/?&authSource=admin" --logpath "/var/log/mongodb/mongod.log"
```
all works. Ubuntu 18.04
Pls try that command.

@thebionicman1 
Hey Steve. Thanks for you reporting on mail. I haven't looked here for a long time ;)
You firewall not allowing golang to dial tcp...
Do you try build on you local machine and copy binary file to server with ftp ot scp? 
After all, you somehow download zip file.
Or use this command:
```
MONALIZE=$( curl --silent "https://api.github.com/repos/MongoDB-Cowboys/Monalize/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' ) \
;wget https://github.com/MongoDB-Cowboys/Monalize/releases/download/$MONALIZE/monalize

```

**Comment by thebionicman1** [comment]
I used that command and got the results that I reported.
Yes, we have a firewall but was wondering whether I could access the binary file in a downloadable way similar to the zip package from github web.
It is easier to have a webaddress where the binary file is and download it into my windows machine and then Transfer it to my unix machine.

**Comment by ku9nov** [comment]
@thebionicman1 if you use this command, you will get binary file, not a zip. 
you shouldn't have gotten the source code.

**Comment by thebionicman1** [comment]
Hi,
The command as it is does not go through due to Firewall so I am trying to see if there is a way to obtain the binary file without going through firewall.
thanks

**Comment by ku9nov** [comment]
@thebionicman1 download binary from here: https://github.com/MongoDB-Cowboys/Monalize/releases/download/1.1.1/monalize
And share it from scp or ftp. In any way that you transfer files to the server.

**Comment by thebionicman1** [comment]
thank you. I have the following now with monalize binary downloaded
-rw-r----- 1 Mike user     9429 Jun  3 01:17 monalize.go
-rw-r----- 1 Mike user    30104 Jun  3 01:17 go.sum
-rw-r----- 1 Mike user     1159 Jun  3 01:17 go.mod
-rw-r----- 1 Mike user     1533 Jun  3 01:17 README.md
-rw-r----- 1 Mike user    35149 Jun  3 01:17 LICENSE
-rwxr-x--- 1 Mike user 17705400 Jun  3 10:06 monalize
 
Can I bypass go build monalize.go and start using monalize binary as is?
Thanks,

**Comment by thebionicman1** [comment]
I have a mongodb running in this machine btw.

**Comment by thebionicman1** [comment]
I tried the following:
knowing that abc760001.source.com:27021 is running 

abc760001> monalize --db_uri "mongodb:abc760001.source.com:27021"
2021/06/03 10:30:59 error parsing uri: scheme must be "mongodb" or "mongodb+srv"

**Comment by ku9nov** [comment]
@thebionicman1 monalize --db_uri "mongodb://127.0.0.1:27017"

**Comment by thebionicman1** [comment]
This worked - Thank you.
Does this sound about right? 
At the end I get:
-rw-r----- 1 Mike user        _**0 Jun  3 10:43 colout.txt**_
[Mongo.pdf](https://github.com/MongoDB-Cowboys/Monalize/files/6593431/Mongo.pdf)

**Comment by ku9nov** [comment]
@thebionicman1 read this:
 https://link.medium.com/WOf82pjhNgb
Aldo read readme.md 
You can find answers here.

**Comment by thebionicman1** [comment]
sorry about that. would you let me know what command would create the second function you have displayed in this page? https://medium.com/mongodb-cowboys/quick-scan-tool-mongodb-monalize-22888e41b1fa  
It is under 2. where it says: The result of the command will be output in terminal and will look like the following:
When I executed my command as such: 
monalize --excel --db_uri "mongodb://10.81.83.41/?&authSource=admin" --logpath /nfs/var/ad_20154501/viper_dev_disk/regression1/log/mongos.2020-09-14T15-13-31
Thanks

**Comment by ku9nov** [comment]
hey)
that command is always running by default. If you don't have slow queries
in the last second the output should be empty.
Thank you. Regards.

вт, 8 июн. 2021 г. в 03:32, thebionicman1 ***@***.***>:

**Comment by thebionicman1** [comment]
Thank you for your reply.
Last questions:
1) if I do not see the output as I described above, then you are saying, I do not have slow queries. But is that what the purpose of the attached screen is?
2) In addition, my colout.txt has tens of entries with many of them have planSummary: COLLSCAN, which means I am not using indexing, and causes high CPU utilization, meaning slow queries, right? then above 1) and 2) do not agree.
3) when I identify a slow query as you clearly described in your article(in orgaddress example), which file do I actually add indexes in order to speed up operation?
Btw, thank you for your reply. That is all I have to get going. My excel by the way does not pop up even though I have -excel in the command line.
Regards

**Comment by ku9nov** [comment]
You need to understand how to work with mongodb.
1. It's just a bonus for you, if at this time when you create a request
dont run a slow query you don't see them in the output. Pls read this:
https://docs.mongodb.com/manual/reference/method/db.currentOp/
2. You used indexes. Thats them list:
--- Collection: ridAll_userMike_t1620773664_tag15887 Count: 2038556
{block_type:1}
{view_name:1}
{depth_key:1}
{group_depth_key:1}
{file_depth_key:1}
{identity:1}
{flow_name:1}
{checktag:1}
{models:1}
{model_filetype:1}
{dbtype:1}
{level:1}
{status:1}
{checknum:1}
{lib_code:1}
{file_name:1}
{parser_status:1}
{input_file:1}
{cell_name:1}
--- Collection: viper_analytic Count: 38
{block_type:1}
{view_name:1}
{depth_key:1}
{group_depth_key:1}
{file_depth_key:1}
{identity:1}
{flow_name:1}
{checktag:1}
{models:1}
{model_filetype:1}
{status:1}
{checknum:1}
{lib_code:1}
{file_name:1}
{parser_status:1}
{input_file:1}
{cell_name:1}
All indexes besides {_id:1} it's  yours.
But maybe they use it wrong. You say you have many writes in collscan logs?
Ok, take our example:
*2020–09–09T21:43:29.931+0530 [conn3] query exampledb.orgaddress query: {
$and: [ { tenantid: “5ed5eede6911f87ea49a221f” }, { status: “Active” } ],
ownerid: { $in: [ “5ed60ea16911f87ea49a741f” ] } } planSummary: COLLSCAN
ntoreturn:0 ntoskip:0 nscanned:105876 nscannedObjects:105876 keyUpdates:0
numYields:0 locks(micros) r:184116 nreturned:1 reslen:84 184ms*
Collection:

*orgaddress*
Actual query performed:








*{    $and: [        { tenantid: "5ed5eede6911f87ea49a221f" },        {
status: "Active" }    ],    ownerid: {      $in: [
"5ed60ea16911f87ea49a741f" ]    }}*
Index to add:

*db.orgaddress.createIndex({ tenantid: 1, status: 1, ownerid: 1 })*
It's if I manually create an index. But indexes are not a cure for all
diseases. Right configured server is very important. Read your logs, and if
you don't have requested indexes in COLLSCAN then create them.
3. Manually creating indexes is just an example. In the real world,
developers create indexes in their apps. I don't know what language and
framework you use. But in their docs you can find how to create indexes in
mongodb.
Thank you. Best Regards.

вт, 8 июн. 2021 г. в 18:17, thebionicman1 ***@***.***>:

**Comment by ku9nov** [comment]
oh really, maybe you don't read it:
https://medium.com/mongodb-cowboys/troubleshooting-mongodb-100-cpu-load-and-slow-queries-da622c6e1339


вт, 8 июн. 2021 г. в 18:44, Sergey Kuyanov ***@***.***>:
